### ISSUE TITLE
webpack编译报错

### ISSUE THREAD

**Issue by lytofb** [hechuanhua/blog#1]
src/index.js和src/js/containers/nav.js中都有引入的组件找不到的错误，目测是大小写搞错了

**Comment by hechuanhua** [comment]
@lytofb 检查了一遍，没发现你说的问题啊

**Comment by lytofb** [comment]
index.js里面引入的Page404和component中的文件名不一致，难道是因为webpack的设置可以忽略大小写？

我改了几个文件的大小写好用的

**Comment by hechuanhua** [comment]
@lytofb 刚刚改了下，但是貌似文件名大小写不对仍然不会报错

**Comment by lytofb** [comment]
你是在windows下运行的么？我看到有评论说

> 迁移到linux服务器上编译源码时，发现找不到vuex模块，原来是window不区分大小写，所以编译通过了

有可能是这个问题

**Comment by hechuanhua** [comment]
@lytofb 恩
