### ISSUE TITLE
运行npm run node时提示nodejs不支持import语法该如何解决？

### ISSUE THREAD

**Issue by ryan-hung** [hechuanhua/blog#4]
楼主你好，
我正在学习react服务端渲染，clone下你的代码之后运行 npm run node 时提示不支持 import 语法？ 请问该如何处理？ 我的nodejs版本是最新的 6.10.0版本。
<img width="589" alt="blog-error" src="https://cloud.githubusercontent.com/assets/10069526/24321374/a30d7d34-1185-11e7-8dfb-079c75ab83c1.png">

万分感激～

**Comment by hechuanhua** [comment]
全局安装babel
然后 npm start

**Comment by ryan-hung** [comment]
谢谢，已解决

**Comment by hechuanhua** [comment]
已解决
